import { describe, it, expect } from 'vitest';
import { generateHtml } from '../src/reporters/html.js';
import { createReportTool } from '../src/tools/report.js';
import type { ScanResult } from '../src/types.js';

function makeScanResult(): ScanResult {
  return {
    findings: [
      {
        id: 'SECRET001',
        title: 'Hardcoded API key detected',
        description: 'API key found in source code',
        severity: 'critical',
        framework: ['soc2', 'hipaa'],
        controlIds: ['CC6.1'],
        file: 'src/config.ts',
        line: 12,
        column: 5,
        evidence: 'const API_KEY = "sk-..."',
        analyzer: 'secret-scanner',
        fixable: false,
      },
      {
        id: 'DEP001',
        title: 'Vulnerable dependency: lodash@4.17.20',
        description: 'Known prototype pollution vulnerability',
        severity: 'high',
        framework: ['soc2'],
        controlIds: ['CC7.1'],
        file: 'package.json',
        line: 15,
        analyzer: 'dependency-auditor',
        fixable: true,
        fix: { description: 'Upgrade lodash to 4.17.21', patch: '' },
      },
      {
        id: 'CFG001',
        title: 'Missing HTTPS enforcement',
        description: 'Server not configured for TLS',
        severity: 'medium',
        framework: ['soc2', 'gdpr'],
        controlIds: ['CC6.7'],
        file: 'src/server.ts',
        line: 3,
        analyzer: 'config-checker',
        fixable: false,
      },
      {
        id: 'CFG002',
        title: 'Debug mode enabled',
        description: 'Debug mode should not be enabled in production',
        severity: 'low',
        framework: ['soc2'],
        controlIds: ['CC7.2'],
        file: '.env',
        line: 1,
        analyzer: 'config-checker',
        fixable: true,
        fix: { description: 'Set DEBUG=false', patch: '' },
      },
      {
        id: 'INFO001',
        title: 'No .gitignore found',
        description: 'Repository lacks a .gitignore file',
        severity: 'info',
        framework: ['soc2'],
        controlIds: ['CC8.1'],
        analyzer: 'git-analyzer',
        fixable: false,
      },
    ],
    summary: {
      total: 5,
      bySeverity: { critical: 1, high: 1, medium: 1, low: 1, info: 1 },
      byFramework: { soc2: 5, hipaa: 1, gdpr: 1 },
      byAnalyzer: {
        'secret-scanner': 1,
        'dependency-auditor': 1,
        'config-checker': 2,
        'git-analyzer': 1,
      },
      fixable: 2,
    },
    metadata: {
      directory: '/tmp/test-project',
      duration: 342,
      analyzersRun: ['secret-scanner', 'dependency-auditor', 'config-checker', 'git-analyzer'],
      frameworks: ['soc2', 'hipaa', 'gdpr'],
      timestamp: '2026-02-26T12:00:00.000Z',
    },
  };
}

describe('HTML reporter', () => {
  it('contains expected sections (executive summary, findings tables)', () => {
    const result = makeScanResult();
    const html = generateHtml(result, 100);

    // Executive summary section
    expect(html).toContain('Executive Summary');
    expect(html).toContain('Scan Date');
    expect(html).toContain('/tmp/test-project');

    // Score
    expect(html).toContain('95%');

    // Findings by severity section
    expect(html).toContain('Findings by Severity');
    expect(html).toContain('CRITICAL (1)');
    expect(html).toContain('HIGH (1)');
    expect(html).toContain('MEDIUM (1)');
    expect(html).toContain('LOW (1)');
    expect(html).toContain('INFO (1)');

    // Individual findings present in table
    expect(html).toContain('Hardcoded API key detected');
    expect(html).toContain('Vulnerable dependency: lodash@4.17.20');
    expect(html).toContain('Missing HTTPS enforcement');

    // Findings by framework section
    expect(html).toContain('Findings by Framework');
    expect(html).toContain('SOC2');
    expect(html).toContain('HIPAA');
    expect(html).toContain('GDPR');
  });

  it('is valid HTML (contains <html>, </html>, <style>)', () => {
    const result = makeScanResult();
    const html = generateHtml(result, 100);

    expect(html).toContain('<html');
    expect(html).toContain('</html>');
    expect(html).toContain('<style>');
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<head>');
    expect(html).toContain('</head>');
    expect(html).toContain('<body>');
    expect(html).toContain('</body>');
  });

  it('contains inline SVG chart for severity distribution', () => {
    const result = makeScanResult();
    const html = generateHtml(result, 100);

    expect(html).toContain('<svg');
    expect(html).toContain('</svg>');
    expect(html).toContain('Severity Distribution');
  });

  it('contains Soul branding in header and footer', () => {
    const result = makeScanResult();
    const html = generateHtml(result, 100);

    expect(html).toContain('Soul Compliance Report');
    expect(html).toContain('Powered by Soul');
    expect(html).toContain('Generated by Soul Compliance');
  });

  it('escapes HTML special characters in finding data', () => {
    const result = makeScanResult();
    result.findings[0].title = 'Test <script>alert("xss")</script>';
    const html = generateHtml(result, 100);

    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;');
  });

  it('shows no findings message when scan is clean', () => {
    const result = makeScanResult();
    result.findings = [];
    result.summary.total = 0;
    result.summary.bySeverity = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    const html = generateHtml(result, 100);

    expect(html).toContain('No findings');
    expect(html).toContain('100%');
  });
});

describe('Report tool', () => {
  it('checks tier gate (throws TierError for free tier)', async () => {
    const tool = createReportTool();

    // Without credentials file, getCurrentTier() returns 'free',
    // so requireTier('pro', ...) will throw TierError.
    await expect(
      tool.execute({ directory: '/tmp/test', format: 'html' }),
    ).rejects.toThrow('HTML/PDF reports requires Soul pro');
  });

  it('registers correctly with expected name and product', () => {
    const tool = createReportTool();

    expect(tool.name).toBe('compliance-report');
    expect(tool.product).toBe('compliance');
    expect(tool.description).toContain('HTML');
    expect(tool.requiresApproval).toBe(false);
    expect(typeof tool.execute).toBe('function');
  });
});
