// AUTO-GENERATED by tools/specgen.go — DO NOT EDIT
// Source: specs/*.yaml

// --- Type Aliases ---

export type ConnectionState = 'connected' | 'connecting' | 'disconnected' | 'error';
export type SessionStatus = 'idle' | 'running' | 'completed' | 'completed_unread';

/** stream */
export interface APIError {
  /** human-readable error */
  message: string;
  /** HTTP status code */
  statusCode: number;
  /** error type from API */
  type: string;
}

/** metrics */
export interface Aggregator {
  /** path to data directory */
  dataDir: string;
}

/** auth */
export interface AuthStatus {
  /** error detail if State is error */
  error: string;
  /** when current token expires (zero if missing) */
  expiresAt: string;
  /** one of: connected, expired, missing, error */
  state: 'connected' | 'expired' | 'missing' | 'error';
}

/** ui-chat */
export interface ChatAttachment {
  name: string;
  mediaType: string;
  data: string; // base64
  preview?: string; // data URL for images
}

/** ui-chat */
export interface ChatInputProps {
  /** disabled during streaming */
  disabled: boolean;
  /** whether a response is currently streaming */
  isStreaming: boolean;
  onSend: (content: string, options?: { model?: string; thinking?: boolean; attachments?: ChatAttachment[] }) => void;
  /** stop the current generation */
  onStop: () => void;
}

/** ui-chat */
export interface ChatViewProps {
  /** current session ID */
  sessionID: string;
}

/** ui-shell */
export interface ConnectionStatusProps {
  /** current connection state */
  status: ConnectionState;
}

/** stream */
export interface ContentBlock {
  /** for type=tool_result */
  content: string;
  /** for type=tool_use */
  id: string;
  /** for type=tool_use */
  input: unknown;
  /** for type=tool_use */
  name: string;
  /** for type=text */
  text: string;
  /** for type=tool_result */
  toolUseID: string;
  /** text, tool_use, tool_result */
  type: string;
}

/** stream */
export interface ContentBlockDelta {
  /** for input_json_delta */
  partialJSON: string;
  /** for text_delta */
  text: string;
  /** text_delta, input_json_delta */
  type: string;
}

/** metrics */
export interface CostSummary {
  /** estimated input token cost (USD) */
  inputCost: number;
  /** estimated output token cost (USD) */
  outputCost: number;
  /** number of API requests */
  requestCount: number;
  /** total estimated cost (USD) */
  totalCost: number;
}

/** metrics */
export interface Event {
  /** event-specific payload */
  data: Record<string, unknown>;
  /** dot-namespaced event type */
  eventType: string;
  /** when event occurred (RFC3339Nano) */
  timestamp: string;
}

/** ws */
export interface InboundMessage {
  /** message content (for chat.send) */
  content: string;
  /** target session (optional, depends on type) */
  sessionID: string;
  /** message type for dispatch */
  type: string;
}

/** session */
export interface Message {
  /** message body (may contain JSON for tool messages) */
  content: string;
  /** when message was stored */
  createdAt: string;
  /** unique message identifier */
  id: string;
  /** model used to generate this message */
  model?: string;
  /** one of: user, assistant, tool_use, tool_result */
  role: 'user' | 'assistant' | 'tool_use' | 'tool_result';
  /** parent session reference */
  sessionID: string;
  /** thinking content from extended thinking (optional) */
  thinking?: string;
  /** tool calls associated with this message */
  toolCalls?: ToolCallData[];
  /** token usage for this message */
  usage?: { inputTokens: number; outputTokens: number; cacheReadInputTokens?: number };
}

/** ui-chat */
export interface MessageBubbleProps {
  /** true for currently streaming message */
  isStreaming: boolean;
  /** message to render */
  message: Message;
  /** callback to edit and resend a message */
  onEdit?: (messageId: string, newContent: string) => void;
  /** callback to retry a message */
  onRetry?: (messageId: string) => void;
  /** search query for text highlighting */
  searchQuery?: string;
}

/** ui-chat */
export interface MessageListProps {
  /** whether a response is in progress */
  isStreaming: boolean;
  /** messages to render */
  messages: Message[];
  /** callback to send a prompt suggestion */
  onSend?: (content: string) => void;
  /** callback to edit and resend a message */
  onEdit?: (messageId: string, newContent: string) => void;
  /** callback to retry a message */
  onRetry?: (messageId: string) => void;
  /** search query for text highlighting */
  searchQuery?: string;
}

/** auth */
export interface OAuthCredentials {
  /** Bearer token for Claude API */
  accessToken: string;
  /** when the access token expires */
  expiresAt: string;
  /** Claude organization identifier */
  orgID: string;
  /** used to obtain new access token */
  refreshToken: string;
}

/** ws */
export interface OutboundMessage {
  /** payload varies by type */
  data: unknown;
  /** which session this relates to */
  sessionID: string;
  /** message type for client dispatch */
  type: string;
}

/** metrics */
export interface Percentiles {
  /** maximum observed */
  max: string;
  /** median latency */
  p50: string;
  /** 90th percentile */
  p90: string;
  /** 99th percentile */
  p99: string;
}

/** stream */
export interface SSEEvent {
  /** for content_block_start */
  contentBlock: ContentBlock | null;
  /** incremental content */
  delta: ContentBlockDelta | null;
  /** for error events */
  error: APIError | null;
  /** content block index */
  index: number;
  /** for message_start */
  message: StreamResponse | null;
  /** message_start, content_block_start, content_block_delta, content_block_stop, message_delta, message_stop, ping, error */
  type: string;
  /** token usage info */
  usage: Usage | null;
}

/** session */
export interface Session {
  /** when session was created */
  createdAt: string;
  /** unique session identifier */
  id: string;
  /** number of messages in session */
  messageCount: number;
  /** current session state */
  status: SessionStatus;
  /** display title, defaults to 'New Session' */
  title: string;
  /** last modification time */
  updatedAt: string;
  lastMessage: string;
  unreadCount: number;
}

/** ui-sessions */
export interface SessionItemProps {
  /** whether this is the selected session */
  isActive: boolean;
  /** delete this session */
  onDelete: () => void;
  /** switch to this session */
  onSwitch: () => void;
  /** session data */
  session: Session;
}

/** ui-sessions */
export interface SessionListProps {
  /** currently selected session */
  activeSessionID: string | null;
  /** create new session */
  onCreate: () => void;
  /** delete session */
  onDelete: (sessionID: string) => void;
  /** switch to session */
  onSwitch: (sessionID: string) => void;
  /** all sessions */
  sessions: Session[];
}

/** session */
export interface Status {
  /** one of: idle, running, completed, completed_unread */
  value: 'idle' | 'running' | 'completed' | 'completed_unread';
}

/** stream */
export interface StreamMessage {
  /** text, tool_use, or tool_result blocks */
  content: ContentBlock[];
  /** user or assistant */
  role: string;
}

/** stream */
export interface StreamRequest {
  /** maximum tokens in response */
  maxTokens: number;
  /** conversation messages */
  messages: Message[];
  /** model identifier override (optional) */
  model: string;
  /** whether to use SSE streaming */
  stream: boolean;
  /** system prompt */
  system: string;
  /** available tool definitions */
  tools: Tool[];
}

/** stream */
export interface StreamResponse {
  /** response content */
  content: ContentBlock[];
  /** message ID */
  id: string;
  /** model used */
  model: string;
  /** always assistant */
  role: string;
  /** end_turn, max_tokens, tool_use */
  stopReason: string;
  /** token counts */
  usage: Usage | null;
}

/** ui-chat */
export interface StreamingIndicatorProps {
  /** whether streaming is active */
  isStreaming: boolean;
}

/** metrics */
export interface TokenSummary {
  /** tokens served from cache */
  cacheHitTokens: number;
  /** total input tokens */
  inputTokens: number;
  /** total output tokens */
  outputTokens: number;
  /** number of API requests */
  totalRequests: number;
}

/** stream */
export interface Tool {
  /** what the tool does */
  description: string;
  /** JSON Schema for tool input */
  inputSchema: unknown;
  /** tool name */
  name: string;
}

/** ui-chat */
export interface ToolCallData {
  /** unique tool call identifier */
  id: string;
  /** tool name */
  name: string;
  /** tool input parameters */
  input: Record<string, unknown>;
  /** current status */
  status: 'running' | 'complete' | 'error';
  /** tool output (when complete or error) */
  output?: string;
  /** progress percentage (0-100) */
  progress?: number;
}

/** ui-chat */
export interface ToolCallBlockProps {
  /** tool call data */
  tool: ToolCallData;
}

/** stream */
export interface Usage {
  /** tokens cached on creation */
  cacheCreationInputTokens: number;
  /** tokens read from cache */
  cacheReadInputTokens: number;
  /** tokens in request */
  inputTokens: number;
  /** tokens in response */
  outputTokens: number;
}

// --- WebSocket Message Types ---

export type InboundMessageType =
  | 'chat.send'
  | 'chat.stop'
  | 'session.switch'
  | 'session.create'
  | 'session.delete'
  | 'session.rename';

export type OutboundMessageType =
  | 'chat.thinking'
  | 'chat.token'
  | 'chat.done'
  | 'chat.error'
  | 'tool.call'
  | 'tool.progress'
  | 'tool.complete'
  | 'tool.error'
  | 'session.created'
  | 'session.deleted'
  | 'session.list'
  | 'session.updated'
  | 'session.history'
  | 'connection.ready';

// --- Manual types (not auto-generated) ---

/** tasks */
export interface Task {
  id: number;
  title: string;
  description: string;
  stage: TaskStage;
  workflow: string;
  product: string;
  metadata: string;
  createdAt: string;
  updatedAt: string;
}

export type TaskStage = 'backlog' | 'active' | 'validation' | 'done' | 'blocked';

/** tasks */
export interface TaskActivity {
  id: number;
  taskId: number;
  eventType: string;
  data: string;
  createdAt: string;
}

// --- Tutor Types ---

export interface TutorTopic {
  id: number;
  module: string;
  category: string;
  name: string;
  difficulty: 'easy' | 'medium' | 'hard';
  contentPath: string;
  status: 'not_started' | 'learning' | 'drilling' | 'mastered';
  createdAt: string;
}

export interface TutorModuleStats {
  module: string;
  topicCount: number;
  completed: number;
  inProgress: number;
  completionPct: number;
  avgScore: number;
}

export interface TutorDashboard {
  readinessPct: number;
  moduleStats: TutorModuleStats[];
  streak: number;
  dueReviewCount: number;
  todayActivity: TutorDailyActivity[] | null;
}

export interface TutorDailyActivity {
  id: number;
  date: string;
  module: string;
  timeSpentSeconds: number;
  sessionsCount: number;
  questionsAnswered: number;
  scoreAvg: number;
}

export interface TutorConfidenceGap {
  topicId: number;
  topicName: string;
  module: string;
  avgSelfRated: number;
  avgActual: number;
  gap: number;
}

export interface TutorAnalytics {
  last30Days: { date: string; activity: TutorDailyActivity[] | null }[];
  confidenceGaps: TutorConfidenceGap[] | null;
}

export interface TutorQuizQuestion {
  id: number;
  topic_id: number;
  difficulty: string;
  question_text: string;
  answer_text: string;
  explanation: string;
}

export interface TutorDrillEvaluation {
  correct: boolean;
  score: number;
  explanation: string;
  expected_keywords: string[];
  matched_keywords: string[];
  next_review: string;
}

export interface TutorMockSession {
  id: number;
  type: 'technical' | 'behavioral' | 'full_loop';
  job_description: string;
  started_at: string;
  completed_at: string | null;
  overall_score: number | null;
  feedback_json: string;
  scores?: { dimension: string; score: number }[];
}

export interface TutorStudyPlan {
  id: number;
  target_role: string;
  target_date: string;
  plan_json: string;
  active: boolean;
}

// ── Projects ──────────────────────────────────────────

export interface Project {
  id: number;
  name: string;
  description: string;
  phase: number;
  status: 'backlog' | 'active' | 'measuring' | 'documenting' | 'shipped';
  week_planned: number;
  hours_estimated: number;
  hours_actual: number;
  github_repo: string;
  readme_url: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectSummary extends Project {
  milestones_done: number;
  milestones_total: number;
  keyword_count: number;
}

export interface Milestone {
  id: number;
  project_id: number;
  name: string;
  description: string;
  acceptance_criteria: string;
  status: 'pending' | 'in_progress' | 'done' | 'skipped';
  completed_at?: string;
  sort_order: number;
}

export interface ProjectMetric {
  id: number;
  project_id: number;
  name: string;
  value: string;
  unit: string;
  captured_at: string;
}

export interface ProjectKeyword {
  id: number;
  project_id?: number;
  keyword: string;
  status: 'claimed' | 'building' | 'shipped';
  claimed_at: string;
  shipped_at?: string;
}

export interface ProfileSync {
  id: number;
  project_id: number;
  platform: string;
  synced: boolean;
  synced_at?: string;
  notes: string;
}

export interface ProjectReadiness {
  id: number;
  project_id: number;
  can_explain: boolean;
  can_demo: boolean;
  can_tradeoffs: boolean;
  self_score: number;
  assessed_at: string;
}

export interface ProjectDashboard {
  total_projects: number;
  shipped: number;
  active: number;
  backlog: number;
  measuring: number;
  documenting: number;
  keywords_total: number;
  keywords_claimed: number;
  keywords_building: number;
  keywords_shipped: number;
  hours_estimated: number;
  hours_actual: number;
  avg_readiness: number;
  projects: ProjectSummary[];
}

export interface ProjectDetail extends Project {
  milestones: Milestone[];
  metrics: ProjectMetric[];
  keywords: ProjectKeyword[];
  syncs: ProfileSync[];
  readiness: ProjectReadiness | null;
}

// ── Observe ──────────────────────────────────────────

export interface ObservePillar {
  name: string;
  description: string;
  constraints: ObserveConstraint[];
  pass: number;
  warn: number;
  fail: number;
  static: number;
  total: number;
}

export interface ObserveConstraint {
  name: string;
  target: string;
  enforcement: string;
  status: 'pass' | 'warn' | 'fail' | 'static';
  value?: string;
}

export interface ObserveOverview {
  status: {
    uptime_seconds: number;
    sessions: number;
    messages: number;
    active_streams: number;
    total_events: number;
    errors: number;
    last_event: string;
  };
  cost: {
    input_tokens: number;
    output_tokens: number;
    requests: number;
    estimated_usd: number;
  };
  alerts: {
    breaches: ObserveAlert[];
  };
}

export interface ObserveAlert {
  timestamp: string;
  metric: string;
  field: string;
  value: number;
  threshold: number;
  severity: string;
}

export interface ObserveTailResponse {
  events: Array<{
    timestamp: string;
    event: string;
    data: Record<string, unknown>;
  }>;
  total: number;
}

export type ObserveTab = 'overview' | 'performant' | 'robust' | 'resilient' | 'secure' | 'sovereign' | 'transparent' | 'tail';
export type ObserveProduct = '' | 'chat' | 'tasks' | 'tutor' | 'projects';
