// AUTO-GENERATED by tools/specgen.go — DO NOT EDIT
// Source: specs/*.yaml

// --- Type Aliases ---

export type ConnectionState = 'connected' | 'connecting' | 'disconnected' | 'error';
export type SessionStatus = 'idle' | 'running' | 'completed' | 'completed_unread';

/** stream */
export interface APIError {
  /** human-readable error */
  message: string;
  /** HTTP status code */
  statusCode: number;
  /** error type from API */
  type: string;
}

/** metrics */
export interface Aggregator {
  /** path to data directory */
  dataDir: string;
}

/** auth */
export interface AuthStatus {
  /** error detail if State is error */
  error: string;
  /** when current token expires (zero if missing) */
  expiresAt: string;
  /** one of: connected, expired, missing, error */
  state: 'connected' | 'expired' | 'missing' | 'error';
}

/** ui-chat */
export interface ChatInputProps {
  /** disabled during streaming */
  disabled: boolean;
  onSend: (content: string) => void;
}

/** ui-chat */
export interface ChatViewProps {
  /** current session ID */
  sessionID: string;
}

/** ui-shell */
export interface ConnectionStatusProps {
  /** current connection state */
  status: ConnectionState;
}

/** stream */
export interface ContentBlock {
  /** for type=tool_result */
  content: string;
  /** for type=tool_use */
  id: string;
  /** for type=tool_use */
  input: unknown;
  /** for type=tool_use */
  name: string;
  /** for type=text */
  text: string;
  /** for type=tool_result */
  toolUseID: string;
  /** text, tool_use, tool_result */
  type: string;
}

/** stream */
export interface ContentBlockDelta {
  /** for input_json_delta */
  partialJSON: string;
  /** for text_delta */
  text: string;
  /** text_delta, input_json_delta */
  type: string;
}

/** metrics */
export interface CostSummary {
  /** estimated input token cost (USD) */
  inputCost: number;
  /** estimated output token cost (USD) */
  outputCost: number;
  /** number of API requests */
  requestCount: number;
  /** total estimated cost (USD) */
  totalCost: number;
}

/** metrics */
export interface Event {
  /** event-specific payload */
  data: Record<string, unknown>;
  /** dot-namespaced event type */
  eventType: string;
  /** when event occurred (RFC3339Nano) */
  timestamp: string;
}

/** ws */
export interface InboundMessage {
  /** message content (for chat.send) */
  content: string;
  /** target session (optional, depends on type) */
  sessionID: string;
  /** message type for dispatch */
  type: string;
}

/** session */
export interface Message {
  /** message body (may contain JSON for tool messages) */
  content: string;
  /** when message was stored */
  createdAt: string;
  /** unique message identifier */
  id: string;
  /** one of: user, assistant, tool_use, tool_result */
  role: 'user' | 'assistant' | 'tool_use' | 'tool_result';
  /** parent session reference */
  sessionID: string;
}

/** ui-chat */
export interface MessageBubbleProps {
  /** true for currently streaming message */
  isStreaming: boolean;
  /** message to render */
  message: Message;
}

/** ui-chat */
export interface MessageListProps {
  /** whether a response is in progress */
  isStreaming: boolean;
  /** messages to render */
  messages: Message[];
}

/** auth */
export interface OAuthCredentials {
  /** Bearer token for Claude API */
  accessToken: string;
  /** when the access token expires */
  expiresAt: string;
  /** Claude organization identifier */
  orgID: string;
  /** used to obtain new access token */
  refreshToken: string;
}

/** ws */
export interface OutboundMessage {
  /** payload varies by type */
  data: unknown;
  /** which session this relates to */
  sessionID: string;
  /** message type for client dispatch */
  type: string;
}

/** metrics */
export interface Percentiles {
  /** maximum observed */
  max: string;
  /** median latency */
  p50: string;
  /** 90th percentile */
  p90: string;
  /** 99th percentile */
  p99: string;
}

/** stream */
export interface SSEEvent {
  /** for content_block_start */
  contentBlock: ContentBlock | null;
  /** incremental content */
  delta: ContentBlockDelta | null;
  /** for error events */
  error: APIError | null;
  /** content block index */
  index: number;
  /** for message_start */
  message: StreamResponse | null;
  /** message_start, content_block_start, content_block_delta, content_block_stop, message_delta, message_stop, ping, error */
  type: string;
  /** token usage info */
  usage: Usage | null;
}

/** session */
export interface Session {
  /** when session was created */
  createdAt: string;
  /** unique session identifier */
  id: string;
  /** number of messages in session */
  messageCount: number;
  /** current session state */
  status: SessionStatus;
  /** display title, defaults to 'New Session' */
  title: string;
  /** last modification time */
  updatedAt: string;
}

/** ui-sessions */
export interface SessionItemProps {
  /** whether this is the selected session */
  isActive: boolean;
  /** delete this session */
  onDelete: () => void;
  /** switch to this session */
  onSwitch: () => void;
  /** session data */
  session: Session;
}

/** ui-sessions */
export interface SessionListProps {
  /** currently selected session */
  activeSessionID: string | null;
  /** create new session */
  onCreate: () => void;
  /** delete session */
  onDelete: (sessionID: string) => void;
  /** switch to session */
  onSwitch: (sessionID: string) => void;
  /** all sessions */
  sessions: Session[];
}

/** session */
export interface Status {
  /** one of: idle, running, completed, completed_unread */
  value: 'idle' | 'running' | 'completed' | 'completed_unread';
}

/** stream */
export interface StreamMessage {
  /** text, tool_use, or tool_result blocks */
  content: ContentBlock[];
  /** user or assistant */
  role: string;
}

/** stream */
export interface StreamRequest {
  /** maximum tokens in response */
  maxTokens: number;
  /** conversation messages */
  messages: Message[];
  /** model identifier override (optional) */
  model: string;
  /** whether to use SSE streaming */
  stream: boolean;
  /** system prompt */
  system: string;
  /** available tool definitions */
  tools: Tool[];
}

/** stream */
export interface StreamResponse {
  /** response content */
  content: ContentBlock[];
  /** message ID */
  id: string;
  /** model used */
  model: string;
  /** always assistant */
  role: string;
  /** end_turn, max_tokens, tool_use */
  stopReason: string;
  /** token counts */
  usage: Usage | null;
}

/** ui-chat */
export interface StreamingIndicatorProps {
  /** whether streaming is active */
  isStreaming: boolean;
}

/** metrics */
export interface TokenSummary {
  /** tokens served from cache */
  cacheHitTokens: number;
  /** total input tokens */
  inputTokens: number;
  /** total output tokens */
  outputTokens: number;
  /** number of API requests */
  totalRequests: number;
}

/** stream */
export interface Tool {
  /** what the tool does */
  description: string;
  /** JSON Schema for tool input */
  inputSchema: unknown;
  /** tool name */
  name: string;
}

/** ui-chat */
export interface ToolCallBlockProps {
  /** tool input parameters */
  input: Record<string, unknown>;
  /** whether detail is shown */
  isExpanded: boolean;
  /** tool name */
  name: string;
  /** tool result (null if pending) */
  result: string | null;
}

/** stream */
export interface Usage {
  /** tokens cached on creation */
  cacheCreationInputTokens: number;
  /** tokens read from cache */
  cacheReadInputTokens: number;
  /** tokens in request */
  inputTokens: number;
  /** tokens in response */
  outputTokens: number;
}

// --- WebSocket Message Types ---

export type InboundMessageType =
  | 'chat.send'
  | 'session.switch'
  | 'session.create'
  | 'session.delete';

export type OutboundMessageType =
  | 'chat.token'
  | 'chat.done'
  | 'chat.error'
  | 'session.created'
  | 'session.deleted'
  | 'session.list'
  | 'session.updated'
  | 'connection.ready';
