// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/soul/v1/product.proto

package soulv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{0}
}

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Tiers         []string               `protobuf:"bytes,4,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Manifest) GetTiers() []string {
	if x != nil {
		return x.Tiers
	}
	return nil
}

type Tool struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,3,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	InputSchemaJson  string                 `protobuf:"bytes,4,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	Tier             string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *Tool) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *Tool) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type ToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ToolRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ToolResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output         string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	StructuredJson string                 `protobuf:"bytes,3,opt,name=structured_json,json=structuredJson,proto3" json:"structured_json,omitempty"`
	Artifacts      []*Artifact            `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResponse) GetStructuredJson() string {
	if x != nil {
		return x.StructuredJson
	}
	return ""
}

func (x *ToolResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ToolEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ToolEvent_Progress
	//	*ToolEvent_Finding
	//	*ToolEvent_Complete
	//	*ToolEvent_Error
	Event         isToolEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *ToolEvent) GetEvent() isToolEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ToolEvent) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ToolEvent) GetFinding() *FindingEvent {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Finding); ok {
			return x.Finding
		}
	}
	return nil
}

func (x *ToolEvent) GetComplete() *ToolResponse {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ToolEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isToolEvent_Event interface {
	isToolEvent_Event()
}

type ToolEvent_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type ToolEvent_Finding struct {
	Finding *FindingEvent `protobuf:"bytes,2,opt,name=finding,proto3,oneof"`
}

type ToolEvent_Complete struct {
	Complete *ToolResponse `protobuf:"bytes,3,opt,name=complete,proto3,oneof"`
}

type ToolEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ToolEvent_Progress) isToolEvent_Event() {}

func (*ToolEvent_Finding) isToolEvent_Event() {}

func (*ToolEvent_Complete) isToolEvent_Event() {}

func (*ToolEvent_Error) isToolEvent_Event() {}

type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyzer      string                 `protobuf:"bytes,1,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressUpdate) GetAnalyzer() string {
	if x != nil {
		return x.Analyzer
	}
	return ""
}

func (x *ProgressUpdate) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	Evidence      string                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingEvent) Reset() {
	*x = FindingEvent{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingEvent) ProtoMessage() {}

func (x *FindingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingEvent.ProtoReflect.Descriptor instead.
func (*FindingEvent) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *FindingEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindingEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindingEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *FindingEvent) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *FindingEvent) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *FindingEvent) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_soul_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_soul_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_soul_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_soul_v1_product_proto protoreflect.FileDescriptor

const file_proto_soul_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/soul/v1/product.proto\x12\asoul.v1\"\a\n" +
	"\x05Empty\"s\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\x05tools\x18\x03 \x03(\v2\r.soul.v1.ToolR\x05tools\x12\x14\n" +
	"\x05tiers\x18\x04 \x03(\tR\x05tiers\"\xa9\x01\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11requires_approval\x18\x03 \x01(\bR\x10requiresApproval\x12*\n" +
	"\x11input_schema_json\x18\x04 \x01(\tR\x0finputSchemaJson\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\"_\n" +
	"\vToolRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x9a\x01\n" +
	"\fToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12'\n" +
	"\x0fstructured_json\x18\x03 \x01(\tR\x0estructuredJson\x12/\n" +
	"\tartifacts\x18\x04 \x03(\v2\x11.soul.v1.ArtifactR\tartifacts\"\xe0\x01\n" +
	"\tToolEvent\x125\n" +
	"\bprogress\x18\x01 \x01(\v2\x17.soul.v1.ProgressUpdateH\x00R\bprogress\x121\n" +
	"\afinding\x18\x02 \x01(\v2\x15.soul.v1.FindingEventH\x00R\afinding\x123\n" +
	"\bcomplete\x18\x03 \x01(\v2\x15.soul.v1.ToolResponseH\x00R\bcomplete\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.soul.v1.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"`\n" +
	"\x0eProgressUpdate\x12\x1a\n" +
	"\banalyzer\x18\x01 \x01(\tR\banalyzer\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x94\x01\n" +
	"\fFindingEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x05 \x01(\x05R\x04line\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\tR\bevidence\"L\n" +
	"\bArtifact\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\":\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xf2\x01\n" +
	"\x0eProductService\x120\n" +
	"\vGetManifest\x12\x0e.soul.v1.Empty\x1a\x11.soul.v1.Manifest\x12:\n" +
	"\vExecuteTool\x12\x14.soul.v1.ToolRequest\x1a\x15.soul.v1.ToolResponse\x12?\n" +
	"\x11ExecuteToolStream\x12\x14.soul.v1.ToolRequest\x1a\x12.soul.v1.ToolEvent0\x01\x121\n" +
	"\x06Health\x12\x0e.soul.v1.Empty\x1a\x17.soul.v1.HealthResponseB1Z/github.com/rishav1305/soul/proto/soul/v1;soulv1b\x06proto3"

var (
	file_proto_soul_v1_product_proto_rawDescOnce sync.Once
	file_proto_soul_v1_product_proto_rawDescData []byte
)

func file_proto_soul_v1_product_proto_rawDescGZIP() []byte {
	file_proto_soul_v1_product_proto_rawDescOnce.Do(func() {
		file_proto_soul_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_soul_v1_product_proto_rawDesc), len(file_proto_soul_v1_product_proto_rawDesc)))
	})
	return file_proto_soul_v1_product_proto_rawDescData
}

var file_proto_soul_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_soul_v1_product_proto_goTypes = []any{
	(*Empty)(nil),          // 0: soul.v1.Empty
	(*Manifest)(nil),       // 1: soul.v1.Manifest
	(*Tool)(nil),           // 2: soul.v1.Tool
	(*ToolRequest)(nil),    // 3: soul.v1.ToolRequest
	(*ToolResponse)(nil),   // 4: soul.v1.ToolResponse
	(*ToolEvent)(nil),      // 5: soul.v1.ToolEvent
	(*ProgressUpdate)(nil), // 6: soul.v1.ProgressUpdate
	(*FindingEvent)(nil),   // 7: soul.v1.FindingEvent
	(*Artifact)(nil),       // 8: soul.v1.Artifact
	(*ErrorEvent)(nil),     // 9: soul.v1.ErrorEvent
	(*HealthResponse)(nil), // 10: soul.v1.HealthResponse
}
var file_proto_soul_v1_product_proto_depIdxs = []int32{
	2,  // 0: soul.v1.Manifest.tools:type_name -> soul.v1.Tool
	8,  // 1: soul.v1.ToolResponse.artifacts:type_name -> soul.v1.Artifact
	6,  // 2: soul.v1.ToolEvent.progress:type_name -> soul.v1.ProgressUpdate
	7,  // 3: soul.v1.ToolEvent.finding:type_name -> soul.v1.FindingEvent
	4,  // 4: soul.v1.ToolEvent.complete:type_name -> soul.v1.ToolResponse
	9,  // 5: soul.v1.ToolEvent.error:type_name -> soul.v1.ErrorEvent
	0,  // 6: soul.v1.ProductService.GetManifest:input_type -> soul.v1.Empty
	3,  // 7: soul.v1.ProductService.ExecuteTool:input_type -> soul.v1.ToolRequest
	3,  // 8: soul.v1.ProductService.ExecuteToolStream:input_type -> soul.v1.ToolRequest
	0,  // 9: soul.v1.ProductService.Health:input_type -> soul.v1.Empty
	1,  // 10: soul.v1.ProductService.GetManifest:output_type -> soul.v1.Manifest
	4,  // 11: soul.v1.ProductService.ExecuteTool:output_type -> soul.v1.ToolResponse
	5,  // 12: soul.v1.ProductService.ExecuteToolStream:output_type -> soul.v1.ToolEvent
	10, // 13: soul.v1.ProductService.Health:output_type -> soul.v1.HealthResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_soul_v1_product_proto_init() }
func file_proto_soul_v1_product_proto_init() {
	if File_proto_soul_v1_product_proto != nil {
		return
	}
	file_proto_soul_v1_product_proto_msgTypes[5].OneofWrappers = []any{
		(*ToolEvent_Progress)(nil),
		(*ToolEvent_Finding)(nil),
		(*ToolEvent_Complete)(nil),
		(*ToolEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_soul_v1_product_proto_rawDesc), len(file_proto_soul_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_soul_v1_product_proto_goTypes,
		DependencyIndexes: file_proto_soul_v1_product_proto_depIdxs,
		MessageInfos:      file_proto_soul_v1_product_proto_msgTypes,
	}.Build()
	File_proto_soul_v1_product_proto = out.File
	file_proto_soul_v1_product_proto_goTypes = nil
	file_proto_soul_v1_product_proto_depIdxs = nil
}
