//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Spec represents the top-level structure of a YAML spec file.
type Spec struct {
	Module   string    `yaml:"module"`
	Language string    `yaml:"language"`
	Types    yaml.Node `yaml:"types"`
}

// TypeDef represents a type definition from a spec.
type TypeDef struct {
	Fields      map[string]string `yaml:"fields"`
	Description string            `yaml:"description"`
	Props       map[string]string `yaml:"props"`
	Types       yaml.Node         `yaml:"types"`
	Variants    yaml.Node         `yaml:"variants"`
}

// TSInterface represents a generated TypeScript interface.
type TSInterface struct {
	Name   string
	Fields []TSField
	Source string
}

// TSField represents a field in a TypeScript interface.
type TSField struct {
	Name    string
	TSType  string
	Comment string
}

// WSMessageType represents a WebSocket message sub-type.
type WSMessageType struct {
	Type        string `yaml:"type"`
	Fields      string `yaml:"fields"`
	Description string `yaml:"description"`
}

// nameConflicts maps type names that appear in multiple modules to module-prefixed names.
// The key is "module:TypeName" and value is the resolved name.
var nameConflicts = map[string]string{
	"stream:Message":  "StreamMessage",
	"stream:Request":  "StreamRequest",
	"stream:Response": "StreamResponse",
}

func main() {
	specDir := "specs"
	outFile := "web/src/lib/types.ts"

	files, err := filepath.Glob(filepath.Join(specDir, "*.yaml"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading specs: %v\n", err)
		os.Exit(1)
	}

	var interfaces []TSInterface
	var wsInbound []WSMessageType
	var wsOutbound []WSMessageType

	// Track all generated interface names to detect conflicts
	nameCount := map[string]int{}

	// First pass: count name occurrences across all specs
	sort.Strings(files)
	for _, file := range files {
		base := filepath.Base(file)
		if base == "pillars.yaml" {
			continue
		}

		data, err := os.ReadFile(file)
		if err != nil {
			continue
		}

		var spec Spec
		if err := yaml.Unmarshal(data, &spec); err != nil {
			continue
		}

		if spec.Types.Kind != yaml.MappingNode {
			continue
		}

		for i := 0; i+1 < len(spec.Types.Content); i += 2 {
			keyNode := spec.Types.Content[i]
			nameCount[keyNode.Value]++
		}
	}

	// Second pass: generate interfaces
	for _, file := range files {
		base := filepath.Base(file)
		if base == "pillars.yaml" {
			continue
		}

		data, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", file, err)
			os.Exit(1)
		}

		var spec Spec
		if err := yaml.Unmarshal(data, &spec); err != nil {
			fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", file, err)
			os.Exit(1)
		}

		if spec.Types.Kind != yaml.MappingNode {
			continue
		}

		for i := 0; i+1 < len(spec.Types.Content); i += 2 {
			keyNode := spec.Types.Content[i]
			valNode := spec.Types.Content[i+1]
			typeName := keyNode.Value

			if valNode.Kind != yaml.MappingNode {
				continue
			}

			var typeDef TypeDef
			if err := valNode.Decode(&typeDef); err != nil {
				continue
			}

			if typeDef.Fields == nil && typeDef.Props == nil {
				continue
			}

			fieldMap := typeDef.Fields
			isUIComponent := spec.Language == "typescript" && typeDef.Props != nil

			if !isUIComponent && shouldSkipType(typeName, fieldMap) {
				continue
			}

			// Resolve name conflicts
			resolvedName := typeName
			if override, ok := nameConflicts[spec.Module+":"+typeName]; ok {
				resolvedName = override
			}

			if isUIComponent {
				iface := buildPropsInterface(resolvedName, typeDef.Props, spec.Module)
				if iface != nil {
					interfaces = append(interfaces, *iface)
				}
				continue
			}

			// Handle WS message sub-types
			if (typeName == "InboundMessage" || typeName == "OutboundMessage") && typeDef.Types.Kind != 0 {
				var msgTypes []WSMessageType
				if err := typeDef.Types.Decode(&msgTypes); err == nil {
					if typeName == "InboundMessage" {
						wsInbound = append(wsInbound, msgTypes...)
					} else {
						wsOutbound = append(wsOutbound, msgTypes...)
					}
				}
			}

			iface := buildInterface(resolvedName, fieldMap, spec.Module)
			if iface != nil {
				interfaces = append(interfaces, *iface)
			}
		}
	}

	// Sort interfaces by name for deterministic output
	sort.Slice(interfaces, func(i, j int) bool {
		return interfaces[i].Name < interfaces[j].Name
	})

	// Generate output
	var out strings.Builder
	out.WriteString("// AUTO-GENERATED by tools/specgen.go — DO NOT EDIT\n")
	out.WriteString("// Source: specs/*.yaml\n\n")

	// Write type aliases for referenced types that aren't generated as interfaces
	out.WriteString("// --- Type Aliases ---\n\n")
	out.WriteString("export type ConnectionState = 'connected' | 'connecting' | 'disconnected' | 'error';\n")
	out.WriteString("export type SessionStatus = 'idle' | 'running' | 'completed' | 'completed_unread';\n")
	out.WriteString("\n")

	// Write interfaces
	for i, iface := range interfaces {
		if i > 0 {
			out.WriteString("\n")
		}
		writeInterface(&out, iface)
	}

	// Write WS message type unions
	if len(wsInbound) > 0 || len(wsOutbound) > 0 {
		out.WriteString("\n// --- WebSocket Message Types ---\n")
	}

	if len(wsInbound) > 0 {
		out.WriteString("\n")
		writeWSMessageTypes(&out, "InboundMessageType", wsInbound)
	}

	if len(wsOutbound) > 0 {
		out.WriteString("\n")
		writeWSMessageTypes(&out, "OutboundMessageType", wsOutbound)
	}

	// Write output file
	if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outFile, []byte(out.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d bytes)\n", outFile, len(out.String()))
}

// shouldSkipType returns true for types that are purely internal Go constructs.
func shouldSkipType(name string, fields map[string]string) bool {
	if fields == nil {
		return true
	}

	goInternalPatterns := []string{
		"*sql.DB", "*http.Client", "*http.Server", "http.Handler",
		"chan ", "chan<-", "<-chan",
		"sync.Mutex", "sync.RWMutex", "sync.WaitGroup",
		"context.CancelFunc", "*os.File",
		"*websocket.Conn",
		"*session.Store", "*stream.Client",
		"auth.OAuthTokenSource",
		"*metrics.EventLogger",
		"*ws.Hub",
	}

	for _, fieldDesc := range fields {
		for _, pattern := range goInternalPatterns {
			if strings.Contains(fieldDesc, pattern) {
				return true
			}
		}
	}

	return false
}

// buildInterface creates a TSInterface from a type's fields map.
func buildInterface(name string, fields map[string]string, module string) *TSInterface {
	if len(fields) == 0 {
		return nil
	}

	iface := &TSInterface{
		Name:   name,
		Source: module,
	}

	fieldNames := make([]string, 0, len(fields))
	for k := range fields {
		fieldNames = append(fieldNames, k)
	}
	sort.Strings(fieldNames)

	for _, fieldName := range fieldNames {
		desc := fields[fieldName]
		tsType, comment := parseFieldType(desc)
		tsFieldName := toTSFieldName(fieldName)

		iface.Fields = append(iface.Fields, TSField{
			Name:    tsFieldName,
			TSType:  tsType,
			Comment: comment,
		})
	}

	return iface
}

// buildPropsInterface creates a TSInterface from a UI component's props map.
func buildPropsInterface(name string, props map[string]string, module string) *TSInterface {
	if len(props) == 0 {
		return nil
	}

	iface := &TSInterface{
		Name:   name + "Props",
		Source: module,
	}

	propNames := make([]string, 0, len(props))
	for k := range props {
		propNames = append(propNames, k)
	}
	sort.Strings(propNames)

	for _, propName := range propNames {
		desc := props[propName]
		tsType, comment := parseFieldType(desc)

		iface.Fields = append(iface.Fields, TSField{
			Name:    propName,
			TSType:  tsType,
			Comment: comment,
		})
	}

	return iface
}

// parseFieldType extracts the TypeScript type and comment from a field description.
func parseFieldType(desc string) (tsType string, comment string) {
	desc = strings.TrimSpace(desc)

	// Split on " — " (em dash) to separate type from description
	parts := strings.SplitN(desc, " — ", 2)
	typeStr := strings.TrimSpace(parts[0])
	if len(parts) > 1 {
		comment = strings.TrimSpace(parts[1])
	}

	// Remove parenthetical annotations like "(UUID)" from type, but not function
	// parameter lists which start with "(" at the beginning of the string.
	if !strings.HasPrefix(typeStr, "(") {
		typeStr = regexp.MustCompile(`\s*\([^)]*\)\s*`).ReplaceAllString(typeStr, " ")
		typeStr = strings.TrimSpace(typeStr)
	}

	// Check for "one of:" pattern which indicates an enum union
	if strings.HasPrefix(typeStr, "string") && strings.Contains(comment, "one of:") {
		idx := strings.Index(comment, "one of:")
		enumPart := strings.TrimSpace(comment[idx+7:])
		values := strings.Split(enumPart, ",")
		var quoted []string
		for _, v := range values {
			v = strings.TrimSpace(v)
			if v != "" {
				quoted = append(quoted, "'"+v+"'")
			}
		}
		if len(quoted) > 0 {
			return strings.Join(quoted, " | "), comment
		}
	}

	tsType = goTypeToTS(typeStr)
	return tsType, comment
}

// goTypeToTS converts a Go type string to a TypeScript type.
func goTypeToTS(goType string) string {
	goType = strings.TrimSpace(goType)

	// Handle pipe-separated unions: "string | null", "idle | running | completed"
	if strings.Contains(goType, " | ") {
		parts := strings.Split(goType, " | ")

		// Check if all parts are primitive TS types or "null" — if so, produce a TS union
		allTS := true
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if p != "null" && p != "string" && p != "number" && p != "boolean" && p != "unknown" {
				// Not a TS primitive, might be enum values
				allTS = false
				break
			}
		}

		if allTS {
			// Already valid TS union (e.g., "string | null")
			var tsParts []string
			for _, p := range parts {
				tsParts = append(tsParts, strings.TrimSpace(p))
			}
			return strings.Join(tsParts, " | ")
		}

		// Otherwise, treat as enum values
		var quoted []string
		allSimple := true
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			if strings.Contains(p, " ") || strings.HasPrefix(p, "*") || strings.Contains(p, "[") {
				allSimple = false
				break
			}
			quoted = append(quoted, "'"+p+"'")
		}
		if allSimple && len(quoted) > 0 {
			return strings.Join(quoted, " | ")
		}
	}

	// Handle function type: "(content: string) → void" or "() → void"
	if strings.Contains(goType, "→") {
		return parseFunctionType(goType)
	}

	// Handle pointer types: *Type → Type | null
	if strings.HasPrefix(goType, "*") {
		inner := goTypeToTS(goType[1:])
		return inner + " | null"
	}

	// Handle slice types: []Type → Type[]
	if strings.HasPrefix(goType, "[]") {
		inner := goTypeToTS(goType[2:])
		return inner + "[]"
	}

	// Handle map types: map[K]V → Record<K, V>
	if strings.HasPrefix(goType, "map[") {
		return parseMapType(goType)
	}

	// Handle known type references
	switch goType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "time.Time", "time.Duration":
		return "string"
	case "any", "interface{}", "json.RawMessage":
		return "unknown"
	case "object":
		return "Record<string, unknown>"
	case "void":
		return "void"
	case "none":
		return "void"
	// Map spec-level type references to generated types
	case "Status":
		return "SessionStatus"
	case "ConnectionState":
		return "ConnectionState"
	case "MessageResponse":
		return "StreamResponse"
	case "Date":
		return "Date"
	}

	// Handle "Type | null" pattern (already TS-like)
	if strings.Contains(goType, " | null") {
		return goType
	}

	// Handle trailing [] like "Message[]"
	if strings.HasSuffix(goType, "[]") {
		inner := goTypeToTS(goType[:len(goType)-2])
		return inner + "[]"
	}

	// Keep type references starting with uppercase
	if len(goType) > 0 && goType[0] >= 'A' && goType[0] <= 'Z' {
		return goType
	}

	// For complex or unknown types, fall back to unknown
	if strings.Contains(goType, " ") {
		return "unknown"
	}

	return goType
}

// parseMapType converts map[K]V to Record<TSKey, TSValue>.
func parseMapType(goType string) string {
	if !strings.HasPrefix(goType, "map[") {
		return "unknown"
	}
	rest := goType[4:]
	bracketDepth := 1
	keyEnd := -1
	for i, ch := range rest {
		if ch == '[' {
			bracketDepth++
		} else if ch == ']' {
			bracketDepth--
			if bracketDepth == 0 {
				keyEnd = i
				break
			}
		}
	}
	if keyEnd < 0 {
		return "Record<string, unknown>"
	}

	keyType := goTypeToTS(rest[:keyEnd])
	valType := goTypeToTS(strings.TrimSpace(rest[keyEnd+1:]))
	return "Record<" + keyType + ", " + valType + ">"
}

// parseFunctionType handles "(content: string) → void" style function types.
func parseFunctionType(goType string) string {
	goType = strings.TrimSpace(goType)

	// Split on " → " to get params and return type
	arrowParts := strings.SplitN(goType, " → ", 2)
	if len(arrowParts) != 2 {
		// Try with just →
		arrowParts = strings.SplitN(goType, "→", 2)
	}

	if len(arrowParts) == 2 {
		paramPart := strings.TrimSpace(arrowParts[0])
		returnPart := strings.TrimSpace(arrowParts[1])

		// Convert return type
		returnTS := goTypeToTS(returnPart)

		// paramPart should be like "(content: string)" or "(sessionID: string)"
		// or "()" for no args
		// or "(message: InboundMessage)"
		// Just pass through param part and convert arrow
		return paramPart + " => " + returnTS
	}

	// Fallback
	return strings.ReplaceAll(goType, "→", "=>")
}

// toTSFieldName converts a Go-style PascalCase field name to TypeScript camelCase.
func toTSFieldName(name string) string {
	if name == "" {
		return name
	}

	// Already camelCase (starts with lowercase)
	if name[0] >= 'a' && name[0] <= 'z' {
		return name
	}

	if name == "ID" {
		return "id"
	}

	// Handle trailing ID: SessionID → sessionID, ToolUseID → toolUseID
	if strings.HasSuffix(name, "ID") && len(name) > 2 {
		prefix := name[:len(name)-2]
		return toLowerFirst(prefix) + "ID"
	}

	runes := []rune(name)
	if len(runes) <= 1 {
		return strings.ToLower(name)
	}

	// Find where the uppercase run ends
	i := 0
	for i < len(runes) && runes[i] >= 'A' && runes[i] <= 'Z' {
		i++
	}

	if i == len(runes) {
		return strings.ToLower(name)
	}

	if i <= 1 {
		return toLowerFirst(name)
	}

	// Multiple uppercase at start (e.g., "CSPHeader") → "cspHeader"
	return strings.ToLower(string(runes[:i-1])) + string(runes[i-1:])
}

func toLowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// writeInterface writes a TSInterface as TypeScript code to the builder.
func writeInterface(out *strings.Builder, iface TSInterface) {
	out.WriteString("/** " + iface.Source + " */\n")
	out.WriteString("export interface " + iface.Name + " {\n")
	for _, field := range iface.Fields {
		if field.Comment != "" {
			out.WriteString("  /** " + field.Comment + " */\n")
		}
		out.WriteString("  " + field.Name + ": " + field.TSType + ";\n")
	}
	out.WriteString("}\n")
}

// writeWSMessageTypes generates a union type for WS message types.
func writeWSMessageTypes(out *strings.Builder, unionName string, messages []WSMessageType) {
	var typeValues []string
	for _, msg := range messages {
		typeValues = append(typeValues, "'"+msg.Type+"'")
	}
	out.WriteString("export type " + unionName + " =\n  | " + strings.Join(typeValues, "\n  | ") + ";\n")
}
